### ISSUE TITLE
Stair Railing Issue Tracker

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#67]
1. [ ] Wierd geometry when step count is set to one. See below.

![Imgur](https://i.imgur.com/LolcvbY.png)

2. [ ] Playing with step height causes the following behaviour:

![Imgur](https://i.imgur.com/tSJ935e.png)

3. [ ] Creating new stairs sometimes results in a weird offset

![Imgur](https://i.imgur.com/53PvlGh.png)

4. [ ] Increasing step width distorts the corner post location on the landing 

![Imgur](https://i.imgur.com/SwpgNH1.png)

**Comment by ranjian0** [comment]
No 1,2,3 fixed by #84
